### ISSUE TITLE
Scripts for BERT fine-tuning

### ISSUE THREAD

**Issue by DRSY** [VITA-Group/BackRazor_Neurips22#1]
Hi,

Thanks for the great work! The method seems very promising in terms of reducing training-time memory when fine-tuning pre-trained language models like BERT. It seems that the repo currently does not contain implementations of BERT? Any plan to release it?

Thanks!

**Comment by geekJZY** [comment]
Hi,

Thanks for your attention. We would release this part this week. Stay tuned.

Thanks!

**Comment by DRSY** [comment]
> 

Thanks! Looking forward to it!

**Comment by geekJZY** [comment]
We have released the code for fine-tuning BERT. Check https://github.com/geekJZY/BackRazor_Bert .
